#!/usr/bin/env bash

# Rename an in-use Jetson account and rebuild the machine identity safely.
set -Eeuo pipefail
umask 022
trap '' HUP

WORK_DIR="/var/lib/robotinit/rename"
STATE_FILE="${WORK_DIR}/state"
APPLY_SCRIPT="${WORK_DIR}/apply.sh"
UNIT_NAME="robotinit-rename.service"
UNIT_FILE="/etc/systemd/system/${UNIT_NAME}"

usage() {
  cat <<'EOF'
用法：sudo ./rename.sh -u <新用户名> -h <新hostname> [选项]

修改正在使用的 Jetson 的用户名、登录界面名称、home 和 hostname，重建
machine-id 与 SSH host key，并清理会标识原机器的缓存和运行状态。

必选参数：
  -u, --user <name>       新用户名
  -h, --hostname <name>   新 hostname

选项：
  --old-user <name>       原用户名；默认读取 SUDO_USER，无法确定时自动找 UID >= 1000 的唯一用户
  --check                 只检查参数、账户冲突和系统环境，不修改系统
  --no-reboot             投递任务但不立即重启，稍后必须手动 reboot
  --yes                   跳过交互确认
  --help                  显示帮助

说明：
  修改会在下一次启动、任何用户登录之前执行。机器会连续启动两次；第二次启动后
  新 machine-id 才会被 PID 1 和所有服务完整使用。SSH host key 也会改变。
EOF
}

die() {
  echo "错误：$*" >&2
  exit 1
}

validate_user_name() {
  local name="$1"
  [[ "$name" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]
}

validate_hostname() {
  local name="$1"
  [[ "$name" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]
}

require_root() {
  if [[ $EUID -ne 0 ]]; then
    die "请使用 sudo 执行本脚本。"
  fi
}

state_value_is_safe() {
  local value="$1"
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]]
}

load_state() {
  local state_path="$1"

  [[ -f "$state_path" ]] || die "任务状态文件不存在：${state_path}"
  [[ "$(stat -c %u "$state_path")" == "0" ]] || die "任务状态文件不属于 root。"
  if (( (8#$(stat -c %a "$state_path") & 8#022) != 0 )); then
    die "任务状态文件不能被 group/other 写入。"
  fi

  # The state is generated by this script as root with shell-escaped values.
  # shellcheck disable=SC1090
  source "$state_path"

  : "${OLD_USER:?}" "${NEW_USER:?}" "${OLD_UID:?}" "${OLD_GID:?}"
  : "${OLD_GROUP:?}" "${RENAME_GROUP:?}" "${OLD_HOME:?}" "${NEW_HOME:?}"
  : "${OLD_HOSTNAME:?}" "${NEW_HOSTNAME:?}" "${BACKUP_DIR:?}"

  validate_user_name "$OLD_USER" || die "状态文件中的原用户名无效。"
  validate_user_name "$NEW_USER" || die "状态文件中的新用户名无效。"
  validate_hostname "$NEW_HOSTNAME" || die "状态文件中的 hostname 无效。"
  [[ "$OLD_UID" =~ ^[0-9]+$ && "$OLD_GID" =~ ^[0-9]+$ ]] || die "状态文件中的 UID/GID 无效。"
  [[ "$RENAME_GROUP" == "0" || "$RENAME_GROUP" == "1" ]] || die "状态文件中的主组设置无效。"
  [[ "$OLD_HOME" == /* && "$NEW_HOME" == /* ]] || die "状态文件中的 home 路径无效。"
  state_value_is_safe "$OLD_HOSTNAME" || die "状态文件中的原 hostname 无效。"
}

backup_file() {
  local path="$1"
  local destination

  [[ -e "$path" || -L "$path" ]] || return 0
  destination="${BACKUP_DIR}${path}"
  [[ -e "$destination" || -L "$destination" ]] && return 0
  mkdir -p "$(dirname "$destination")"
  cp -a -- "$path" "$destination"
}

backup_initial_state() {
  local path

  mkdir -p "$BACKUP_DIR"
  chmod 0700 "$BACKUP_DIR"
  [[ -e "${BACKUP_DIR}/.account-databases-saved" ]] && return 0

  for path in \
    /etc/passwd \
    /etc/shadow \
    /etc/group \
    /etc/gshadow \
    /etc/subuid \
    /etc/subgid \
    /etc/hostname \
    /etc/hosts \
    /etc/machine-id \
    /var/lib/dbus/machine-id; do
    backup_file "$path"
  done

  if [[ -d /etc/ssh ]]; then
    while IFS= read -r -d '' path; do
      backup_file "$path"
    done < <(find /etc/ssh -maxdepth 1 -type f -name 'ssh_host_*' -print0)
  fi

  touch "${BACKUP_DIR}/.account-databases-saved"
}

escape_sed_pattern() {
  printf '%s' "$1" | sed 's/[][\\.^$*+?{}()|#]/\\&/g'
}

escape_sed_replacement() {
  printf '%s' "$1" | sed 's/[\\&#]/\\&/g'
}

replace_literal_in_file() {
  local file="$1"
  local old_value="$2"
  local new_value="$3"
  local old_pattern new_replacement

  [[ -f "$file" ]] || return 0
  LC_ALL=C grep -IqF -- "$old_value" "$file" || return 0
  backup_file "$file"
  old_pattern="$(escape_sed_pattern "$old_value")"
  new_replacement="$(escape_sed_replacement "$new_value")"
  sed -i -E -e "s#${old_pattern}#${new_replacement}#g" "$file"
}

replace_user_token_in_file() {
  local file="$1"
  local old_pattern new_replacement

  [[ -f "$file" ]] || return 0
  LC_ALL=C grep -IqF -- "$OLD_USER" "$file" || return 0
  backup_file "$file"
  old_pattern="$(escape_sed_pattern "$OLD_USER")"
  new_replacement="$(escape_sed_replacement "$NEW_USER")"
  while LC_ALL=C grep -Eq \
    "(^|[^[:alnum:]_.-])${old_pattern}([^[:alnum:]_.-]|$)" "$file"; do
    sed -i -E \
      -e "s#(^|[^[:alnum:]_.-])${old_pattern}([^[:alnum:]_.-]|$)#\\1${new_replacement}\\2#g" \
      "$file"
  done
}

rewrite_literal_tree() {
  local old_value="$1"
  local new_value="$2"
  shift 2
  local root file
  local directory_roots=()

  [[ "$old_value" != "$new_value" ]] || return 0
  for root in "$@"; do
    [[ -e "$root" ]] || continue
    if [[ -f "$root" ]]; then
      replace_literal_in_file "$root" "$old_value" "$new_value"
      continue
    fi
    directory_roots+=("$root")
  done

  ((${#directory_roots[@]} > 0)) || return 0
  while IFS= read -r -d '' file; do
    [[ "$file" == "$WORK_DIR"/* ]] && continue
    replace_literal_in_file "$file" "$old_value" "$new_value"
  done < <(
    find "${directory_roots[@]}" -xdev -type f -size -8M -readable -print0 2>/dev/null |
      xargs -0 -r grep -IlZF -- "$old_value"
  )
}

rewrite_user_config_roots() {
  local root file
  local directory_roots=()
  local roots=(
    /etc/gdm3
    /etc/lightdm
    /etc/sddm.conf
    /etc/sddm.conf.d
    /etc/systemd/system
    /etc/polkit-1/rules.d
    /etc/sudoers
    /etc/sudoers.d
    /etc/security
    /etc/cron.d
    /etc/udev/rules.d
    /etc/tmpfiles.d
    /etc/NetworkManager/dispatcher.d
    "${NEW_HOME}/.config"
    "${NEW_HOME}/.local"
    "${NEW_HOME}/.bashrc"
    "${NEW_HOME}/.profile"
    "${NEW_HOME}/.zshrc"
    "${NEW_HOME}/.gitconfig"
    /var/lib/AccountsService/users
  )

  [[ "$OLD_USER" != "$NEW_USER" ]] || return 0
  for root in "${roots[@]}"; do
    [[ -e "$root" ]] || continue
    if [[ -f "$root" ]]; then
      [[ "$root" == "$UNIT_FILE" ]] || replace_user_token_in_file "$root"
      continue
    fi
    directory_roots+=("$root")
  done

  ((${#directory_roots[@]} > 0)) || return 0
  while IFS= read -r -d '' file; do
    [[ "$file" == "$UNIT_FILE" || "$file" == "$WORK_DIR"/* ]] && continue
    replace_user_token_in_file "$file"
  done < <(
    find "${directory_roots[@]}" -xdev -type f -size -8M -readable -print0 2>/dev/null |
      xargs -0 -r grep -IlZF -- "$OLD_USER"
  )
}

rewrite_group_members() {
  local file="$1"
  local temporary

  [[ "$OLD_USER" != "$NEW_USER" && -f "$file" ]] || return 0
  awk -F: -v OFS=: -v old="$OLD_USER" -v new="$NEW_USER" '
    {
      count = split($4, members, ",")
      result = ""
      for (i = 1; i <= count; i++) {
        if (members[i] == old) members[i] = new
        if (members[i] != "") result = result (result == "" ? "" : ",") members[i]
      }
      $4 = result
      print
    }
  ' "$file" > "${file}.robotinit-tmp"
  temporary="${file}.robotinit-tmp"
  chown --reference="$file" "$temporary"
  chmod --reference="$file" "$temporary"
  mv -f -- "$temporary" "$file"
}

rewrite_subid_owner() {
  local file="$1"
  local temporary

  [[ "$OLD_USER" != "$NEW_USER" && -f "$file" ]] || return 0
  if ! awk -F: -v old="$OLD_USER" '$1 == old { found = 1 } END { exit !found }' "$file"; then
    return 0
  fi
  backup_file "$file"
  awk -F: -v OFS=: -v old="$OLD_USER" -v new="$NEW_USER" \
    '$1 == old { $1 = new } { print }' "$file" > "${file}.robotinit-tmp"
  temporary="${file}.robotinit-tmp"
  chown --reference="$file" "$temporary"
  chmod --reference="$file" "$temporary"
  mv -f -- "$temporary" "$file"
}

move_named_path() {
  local old_path="$1"
  local new_path="$2"

  [[ "$old_path" != "$new_path" ]] || return 0
  [[ -e "$old_path" || -L "$old_path" ]] || return 0
  if [[ -e "$new_path" || -L "$new_path" ]]; then
    die "无法迁移 ${old_path}：目标已存在：${new_path}"
  fi
  backup_file "$old_path"
  mkdir -p "$(dirname "$new_path")"
  mv -- "$old_path" "$new_path"
}

rewrite_home_symlinks() {
  local link target new_target

  [[ "$OLD_HOME" != "$NEW_HOME" && -d "$NEW_HOME" ]] || return 0
  while IFS= read -r -d '' link; do
    target="$(readlink -- "$link")"
    case "$target" in
      "$OLD_HOME" | "$OLD_HOME"/*)
        new_target="${NEW_HOME}${target#"$OLD_HOME"}"
        ln -sfn -- "$new_target" "$link"
        ;;
    esac
  done < <(find "$NEW_HOME" -xdev -type l -print0 2>/dev/null)
}

clear_directory_contents() {
  local directory="$1"
  [[ -d "$directory" ]] || return 0
  find "$directory" -xdev -mindepth 1 -delete 2>/dev/null || true
}

set_hostname_files() {
  local old_pattern new_replacement

  printf '%s\n' "$NEW_HOSTNAME" > /etc/hostname
  chmod 0644 /etc/hostname
  chown root:root /etc/hostname
  hostname "$NEW_HOSTNAME"
  replace_literal_in_file /etc/machine-info "$OLD_HOSTNAME" "$NEW_HOSTNAME"

  touch /etc/hosts
  if [[ -n "$OLD_HOSTNAME" && "$OLD_HOSTNAME" != "$NEW_HOSTNAME" ]]; then
    old_pattern="$(escape_sed_pattern "$OLD_HOSTNAME")"
    new_replacement="$(escape_sed_replacement "$NEW_HOSTNAME")"
    while grep -Eq "(^|[[:space:]])${old_pattern}([[:space:]]|$)" /etc/hosts; do
      sed -i -E \
        -e "s#(^|[[:space:]])${old_pattern}([[:space:]]|$)#\\1${new_replacement}\\2#g" \
        /etc/hosts
    done
  fi
  if ! awk -v name="$NEW_HOSTNAME" '
    $1 == "127.0.1.1" {
      for (i = 2; i <= NF; i++) if ($i == name) found = 1
    }
    END { exit !found }
  ' /etc/hosts; then
    printf '127.0.1.1\t%s\n' "$NEW_HOSTNAME" >> /etc/hosts
  fi
  chmod 0644 /etc/hosts
  chown root:root /etc/hosts

  if command -v cloud-init >/dev/null 2>&1; then
    backup_file /etc/cloud/cloud.cfg.d/99-robotinit-hostname.cfg
    mkdir -p /etc/cloud/cloud.cfg.d
    printf '%s\n' 'preserve_hostname: true' > /etc/cloud/cloud.cfg.d/99-robotinit-hostname.cfg
    chmod 0644 /etc/cloud/cloud.cfg.d/99-robotinit-hostname.cfg
  fi
}

rebuild_machine_id() {
  local machine_id

  rm -f /etc/machine-id /var/lib/dbus/machine-id
  machine_id="$(tr -d '-' </proc/sys/kernel/random/uuid)"
  [[ "$machine_id" =~ ^[0-9a-f]{32}$ ]] || die "随机 machine-id 生成失败。"
  printf '%s\n' "$machine_id" > /etc/machine-id
  chmod 0444 /etc/machine-id
  chown root:root /etc/machine-id
  mkdir -p /var/lib/dbus
  ln -sfn /etc/machine-id /var/lib/dbus/machine-id
}

rebuild_ssh_host_keys() {
  command -v ssh-keygen >/dev/null 2>&1 || die "缺少 ssh-keygen。"
  rm -f /etc/ssh/ssh_host_*
  ssh-keygen -q -A
  compgen -G '/etc/ssh/ssh_host_*_key.pub' >/dev/null || die "SSH host key 生成失败。"
}

clean_machine_state() {
  local state_dir

  systemctl stop NetworkManager.service 2>/dev/null || true
  systemctl stop systemd-timesyncd.service chrony.service bluetooth.service 2>/dev/null || true

  rm -f \
    /var/lib/systemd/random-seed \
    /var/lib/systemd/credential.secret \
    /var/lib/urandom/random-seed \
    /var/lib/libuuid/clock.txt \
    /opt/nvidia/l4t-usb-device-mode/mac-addresses

  for state_dir in \
    /var/lib/NetworkManager \
    /var/lib/bluetooth \
    /var/lib/systemd/rfkill \
    /var/lib/systemd/backlight \
    /var/lib/systemd/timesync \
    /var/lib/systemd/timers \
    /var/lib/chrony \
    /var/lib/ntp \
    /var/lib/pulse \
    /var/lib/avahi-autoipd \
    /var/lib/systemd/coredump \
    /var/crash; do
    clear_directory_contents "$state_dir"
  done

  if [[ -d /var/lib/dhcp ]]; then
    find /var/lib/dhcp -xdev -type f -name '*.lease*' -delete 2>/dev/null || true
  fi

  clear_directory_contents "${NEW_HOME}/.nv/ComputeCache"
  clear_directory_contents "${NEW_HOME}/.config/Code/Cache"
  clear_directory_contents "${NEW_HOME}/.config/Code/CachedData"
  clear_directory_contents "${NEW_HOME}/.config/pulse"
  clear_directory_contents "${NEW_HOME}/.vscode-server/data/logs"
  clear_directory_contents "${NEW_HOME}/.vscode-server/data/CachedData"
  clear_directory_contents "${NEW_HOME}/.ros/log"
  rm -f \
    "${NEW_HOME}/.local/share/recently-used.xbel" \
    "${NEW_HOME}/.config/Code/machineid" \
    "${NEW_HOME}/.config/Code - OSS/machineid" \
    "${NEW_HOME}/.vscode-server/data/machineid" \
    "${NEW_HOME}/.pulse-cookie" \
    "${NEW_HOME}/.Xauthority" \
    "${NEW_HOME}/.ICEauthority" \
    "${NEW_HOME}/.sudo_as_admin_successful" \
    "${NEW_HOME}/.motd_shown"

  clear_directory_contents /tmp
  clear_directory_contents /var/tmp
}

clear_old_logs() {
  journalctl --rotate 2>/dev/null || true
  journalctl --vacuum-time=1s 2>/dev/null || true
  systemctl stop rsyslog.service 2>/dev/null || true

  if [[ -d /var/log/journal ]]; then
    find /var/log/journal -xdev -mindepth 1 -delete 2>/dev/null || true
  fi
  find /var/log -xdev -type f ! -path '/var/log/journal/*' \
    -exec truncate -s 0 {} + 2>/dev/null || true
  clear_directory_contents /var/spool/rsyslog
  rm -f /var/lib/rsyslog/imjournal.state /var/lib/logrotate/status
}

write_residual_report() {
  local report="${WORK_DIR}/residual-report.txt"
  local root file
  local roots=(/etc /usr/local /opt "$NEW_HOME")
  local directory_roots=()

  : > "$report"
  printf '迁移完成后的旧 home 路径文本引用（应为空；二进制文件不会自动修改）：\n' >> "$report"
  for root in "${roots[@]}"; do
    [[ -e "$root" ]] || continue
    if [[ -f "$root" ]]; then
      LC_ALL=C grep -IlF -- "$OLD_HOME" "$root" >> "$report" 2>/dev/null || true
      continue
    fi
    directory_roots+=("$root")
  done
  if ((${#directory_roots[@]} > 0)); then
    while IFS= read -r -d '' file; do
      [[ "$file" == "$WORK_DIR"/* ]] && continue
      printf '%s\n' "$file" >> "$report"
    done < <(
      find "${directory_roots[@]}" -xdev -type f -size -8M -readable -print0 2>/dev/null |
        xargs -0 -r grep -IlZF -- "$OLD_HOME"
    )
  fi
  printf '\n不会自动修改的二进制文件中可能仍含历史路径；项目数据和个人 SSH 密钥均已保留。\n' >> "$report"
  chmod 0600 "$report"
}

apply_changes() {
  local state_path="$1"
  local current_uid current_home current_group current_gid
  local old_account_exists=0 new_account_exists=0
  local new_machine_id

  require_root
  load_state "$state_path"
  mkdir -p "$WORK_DIR"
  exec 9>"${WORK_DIR}/apply.lock"
  flock -n 9 || die "已有身份迁移任务正在执行。"
  exec > >(tee -a "${WORK_DIR}/apply.log") 2>&1

  APPLY_COMPLETE=0
  on_apply_exit() {
    local exit_code=$?
    if ((exit_code == 0 || APPLY_COMPLETE)); then
      return
    fi
    set +e
    printf 'status=failed\nfailed-at=%s\nexit-code=%s\n' \
      "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$exit_code" > "${WORK_DIR}/status"
    echo
    echo "身份迁移失败（脚本第 ${BASH_LINENO[0]} 行，退出码 ${exit_code}）。"
    echo "备份：${BACKUP_DIR}"
    echo "日志：${WORK_DIR}/apply.log"
    echo "任务会保留并在下次启动时重试。"
  }
  trap on_apply_exit EXIT

  echo "==> 保存账户数据库和机器身份备份"
  backup_initial_state

  getent passwd "$OLD_USER" >/dev/null 2>&1 && old_account_exists=1
  getent passwd "$NEW_USER" >/dev/null 2>&1 && new_account_exists=1
  if ((old_account_exists && new_account_exists)) && [[ "$OLD_USER" != "$NEW_USER" ]]; then
    die "原用户和新用户同时存在，拒绝继续。"
  fi

  echo "==> 迁移登录账户、home 和主组"
  if [[ "$OLD_USER" != "$NEW_USER" ]] && ((old_account_exists)); then
    usermod --login "$NEW_USER" --home "$NEW_HOME" --move-home --comment "$NEW_USER" "$OLD_USER"
  fi

  getent passwd "$NEW_USER" >/dev/null 2>&1 || die "迁移后找不到用户 ${NEW_USER}。"
  current_uid="$(id -u "$NEW_USER")"
  [[ "$current_uid" == "$OLD_UID" ]] || die "新用户 UID 与原 UID 不一致。"
  current_home="$(getent passwd "$NEW_USER" | cut -d: -f6)"
  if [[ "$current_home" != "$NEW_HOME" ]]; then
    if [[ -d "$OLD_HOME" && ! -e "$NEW_HOME" ]]; then
      usermod --home "$NEW_HOME" --move-home "$NEW_USER"
    elif [[ -d "$NEW_HOME" ]]; then
      usermod --home "$NEW_HOME" "$NEW_USER"
    else
      die "无法完成 home 迁移：${OLD_HOME} -> ${NEW_HOME}"
    fi
  fi
  usermod --comment "$NEW_USER" "$NEW_USER"

  if ((RENAME_GROUP)); then
    if getent group "$OLD_GROUP" >/dev/null 2>&1 && [[ "$OLD_GROUP" != "$NEW_USER" ]]; then
      if getent group "$NEW_USER" >/dev/null 2>&1; then
        current_gid="$(getent group "$NEW_USER" | cut -d: -f3)"
        [[ "$current_gid" == "$OLD_GID" ]] || die "新主组已存在且 GID 不匹配。"
      else
        groupmod --new-name "$NEW_USER" "$OLD_GROUP"
      fi
    fi
    current_group="$(id -gn "$NEW_USER")"
    [[ "$current_group" == "$NEW_USER" ]] || die "主组名称迁移失败。"
  fi

  backup_file /etc/group
  backup_file /etc/gshadow
  rewrite_group_members /etc/group
  rewrite_group_members /etc/gshadow
  rewrite_subid_owner /etc/subuid
  rewrite_subid_owner /etc/subgid

  move_named_path "/var/spool/cron/crontabs/${OLD_USER}" "/var/spool/cron/crontabs/${NEW_USER}"
  move_named_path "/var/lib/systemd/linger/${OLD_USER}" "/var/lib/systemd/linger/${NEW_USER}"
  move_named_path "/var/lib/AccountsService/users/${OLD_USER}" "/var/lib/AccountsService/users/${NEW_USER}"
  move_named_path "/var/lib/AccountsService/icons/${OLD_USER}" "/var/lib/AccountsService/icons/${NEW_USER}"
  move_named_path "/var/lib/lightdm-data/${OLD_USER}" "/var/lib/lightdm-data/${NEW_USER}"
  move_named_path "/var/mail/${OLD_USER}" "/var/mail/${NEW_USER}"
  if [[ ! -L /var/spool/mail ]]; then
    move_named_path "/var/spool/mail/${OLD_USER}" "/var/spool/mail/${NEW_USER}"
  fi

  echo "==> 更新登录界面、自动登录、服务和旧 home 路径"
  rewrite_literal_tree "$OLD_HOME" "$NEW_HOME" /etc /usr/local /opt "$NEW_HOME"
  rewrite_user_config_roots
  rewrite_home_symlinks
  if command -v visudo >/dev/null 2>&1; then
    visudo -cf /etc/sudoers >/dev/null
  fi
  systemctl daemon-reload

  echo "==> 设置 hostname"
  set_hostname_files

  echo "==> 重建 machine-id 和 SSH host key"
  rebuild_machine_id
  rebuild_ssh_host_keys

  echo "==> 生成旧路径残留报告"
  write_residual_report

  echo "==> 清理每机唯一状态、旧路径缓存和日志"
  clean_machine_state
  clear_old_logs

  new_machine_id="$(cat /etc/machine-id)"
  mkdir -p /var/lib/robotinit
  {
    printf 'old-user=%s\n' "$OLD_USER"
    printf 'user=%s\n' "$NEW_USER"
    printf 'old-hostname=%s\n' "$OLD_HOSTNAME"
    printf 'hostname=%s\n' "$NEW_HOSTNAME"
    printf 'machine-id=%s\n' "$new_machine_id"
    date -u '+renamed-at=%Y-%m-%dT%H:%M:%SZ'
  } > /var/lib/robotinit/identity
  chmod 0600 /var/lib/robotinit/identity
  printf 'status=complete\ncompleted-at=%s\n' \
    "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "${WORK_DIR}/status"

  echo "==> 迁移完成，将进行第二次启动"
  rm -f "/etc/systemd/system/multi-user.target.wants/${UNIT_NAME}"
  rm -f "$UNIT_FILE" "$STATE_FILE" "$APPLY_SCRIPT"
  systemctl daemon-reload || true
  sync
  APPLY_COMPLETE=1
  if ! systemctl reboot; then
    printf 'status=complete-reboot-required\ncompleted-at=%s\n' \
      "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "${WORK_DIR}/status"
    echo "身份迁移已完成，但自动重启失败。请立即手动执行 reboot。"
  fi
}

if [[ "${1:-}" == "--apply" ]]; then
  [[ $# -eq 2 ]] || die "内部参数错误。"
  apply_changes "$2"
  exit 0
fi

NEW_USER=""
NEW_HOSTNAME=""
OLD_USER=""
CHECK_ONLY=0
NO_REBOOT=0
ASSUME_YES=0

while (($# > 0)); do
  case "$1" in
    -u | --user)
      [[ $# -ge 2 ]] || die "$1 缺少参数。"
      NEW_USER="$2"
      shift 2
      ;;
    -h | --hostname)
      [[ $# -ge 2 ]] || die "$1 缺少参数。"
      NEW_HOSTNAME="$2"
      shift 2
      ;;
    --old-user)
      [[ $# -ge 2 ]] || die "--old-user 缺少参数。"
      OLD_USER="$2"
      shift 2
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    --no-reboot)
      NO_REBOOT=1
      shift
      ;;
    --yes)
      ASSUME_YES=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "错误：未知参数：$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_root

if [[ ! -r /etc/nv_tegra_release ]]; then
  die "当前系统不是可识别的 Jetson Linux，拒绝执行。"
fi
[[ -d /run/systemd/system ]] || die "当前系统不是由 systemd 启动。"

validate_user_name "$NEW_USER" || {
  echo "错误：新用户名必须为 1-32 位小写字母、数字、下划线或连字符，且首字符只能是小写字母或下划线。" >&2
  exit 2
}
validate_hostname "$NEW_HOSTNAME" || {
  echo "错误：hostname 必须为 1-63 位小写字母、数字或连字符，且不能以连字符开头/结尾。" >&2
  exit 2
}

if [[ -z "$OLD_USER" && -n "${SUDO_USER:-}" && "$SUDO_USER" != "root" ]]; then
  OLD_USER="$SUDO_USER"
fi
if [[ -z "$OLD_USER" ]]; then
  mapfile -t LOGIN_USERS < <(
    getent passwd | awk -F: \
      '$3 >= 1000 && $3 < 65534 && $6 ~ /^\/home\// && $7 !~ /(nologin|false)$/ { print $1 }'
  )
  if ((${#LOGIN_USERS[@]} == 1)); then
    OLD_USER="${LOGIN_USERS[0]}"
  else
    die "无法唯一确定原用户，请添加 --old-user <name>。"
  fi
fi
validate_user_name "$OLD_USER" || die "原用户名不符合脚本支持的格式：${OLD_USER}"
getent passwd "$OLD_USER" >/dev/null 2>&1 || die "原用户不存在：${OLD_USER}"

OLD_UID="$(id -u "$OLD_USER")"
OLD_GID="$(id -g "$OLD_USER")"
((OLD_UID >= 1000 && OLD_UID < 65534)) || die "拒绝修改系统账户或 root：${OLD_USER}"
OLD_HOME="$(getent passwd "$OLD_USER" | cut -d: -f6)"
[[ "$OLD_HOME" == /* && "$OLD_HOME" != "/" && -d "$OLD_HOME" ]] || die "原 home 无效：${OLD_HOME}"
NEW_HOME="$(dirname "$OLD_HOME")/${NEW_USER}"
OLD_GROUP="$(getent group "$OLD_GID" | cut -d: -f1)"
[[ -n "$OLD_GROUP" ]] || die "无法确定原用户的主组。"
RENAME_GROUP=0
[[ "$OLD_GROUP" == "$OLD_USER" ]] && RENAME_GROUP=1
OLD_HOSTNAME="$(hostnamectl --static 2>/dev/null || hostname)"
BACKUP_DIR="${WORK_DIR}/backup"

if [[ "$NEW_USER" != "$OLD_USER" ]]; then
  getent passwd "$NEW_USER" >/dev/null 2>&1 && die "新用户名已存在：${NEW_USER}"
  [[ ! -e "$NEW_HOME" && ! -L "$NEW_HOME" ]] || die "新 home 已存在：${NEW_HOME}"
  [[ ! -e "/var/spool/cron/crontabs/${NEW_USER}" ]] || die "新用户名的 crontab 已存在。"
  [[ ! -e "/var/lib/AccountsService/users/${NEW_USER}" ]] || die "新用户名的 AccountsService 配置已存在。"
  if ((RENAME_GROUP)) && getent group "$NEW_USER" >/dev/null 2>&1; then
    die "新主组名称已存在：${NEW_USER}"
  fi
fi

for command_name in \
  awk cp find flock getent grep hostname install mv sed ssh-keygen stat systemctl tee usermod xargs; do
  command -v "$command_name" >/dev/null 2>&1 || die "缺少系统命令：${command_name}"
done
if ((RENAME_GROUP)); then
  command -v groupmod >/dev/null 2>&1 || die "缺少系统命令：groupmod"
fi
if command -v pdbedit >/dev/null 2>&1 && pdbedit -L "$OLD_USER" >/dev/null 2>&1; then
  die "检测到 Samba 用户 ${OLD_USER}。Samba 密码数据库不能安全地自动改名，请先迁移或删除该 Samba 账户。"
fi

if [[ -e "$STATE_FILE" || -e "$UNIT_FILE" ]]; then
  die "已有未完成的迁移任务。请查看 ${WORK_DIR}/status 和 apply.log；修复后重启会自动重试。"
fi

echo "检查通过："
echo "  用户名：${OLD_USER} (UID ${OLD_UID}) -> ${NEW_USER}"
echo "  主组：${OLD_GROUP} (GID ${OLD_GID})$([[ "$RENAME_GROUP" == 1 ]] && printf ' -> %s' "$NEW_USER")"
echo "  home：${OLD_HOME} -> ${NEW_HOME}"
echo "  hostname：${OLD_HOSTNAME} -> ${NEW_HOSTNAME}"
echo "  显示管理器：$(systemctl show display-manager.service -p Id --value 2>/dev/null || echo 未检测到)"

if ((CHECK_ONLY)); then
  echo "只检查模式：未修改系统。"
  exit 0
fi

SCRIPT_SOURCE="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || true)"
if [[ -z "$SCRIPT_SOURCE" || ! -f "$SCRIPT_SOURCE" || "$SCRIPT_SOURCE" == /dev/* ]]; then
  die "无法投递离线任务。请先将脚本下载为本地文件，再使用 sudo 执行；不支持 curl | sudo bash。"
fi

if ((!ASSUME_YES)); then
  if [[ ! -r /dev/tty ]]; then
    die "无法交互确认；自动化执行请添加 --yes。"
  fi
  cat >/dev/tty <<EOF

警告：这会中断当前 SSH/桌面会话，连续重启两次，并改变 SSH host key。
用户数据和网络连接 profile 会保留；旧日志、机器唯一状态和相关缓存会清理。
输入 RENAME 继续：
EOF
  read -r answer </dev/tty
  [[ "$answer" == "RENAME" ]] || {
    echo "已取消。"
    exit 0
  }
fi

mkdir -p "$WORK_DIR"
chmod 0700 "$WORK_DIR"

STAGING=1
on_stage_error() {
  local exit_code=$?
  if ((STAGING)); then
    systemctl disable "$UNIT_NAME" >/dev/null 2>&1 || true
    rm -f "$UNIT_FILE" "$STATE_FILE" "$APPLY_SCRIPT" || true
    systemctl daemon-reload >/dev/null 2>&1 || true
    echo "任务投递失败，已清理未完成的任务文件。" >&2
  fi
  exit "$exit_code"
}
trap on_stage_error ERR

install -m 0700 -o root -g root "$SCRIPT_SOURCE" "$APPLY_SCRIPT"

{
  printf 'OLD_USER=%q\n' "$OLD_USER"
  printf 'NEW_USER=%q\n' "$NEW_USER"
  printf 'OLD_UID=%q\n' "$OLD_UID"
  printf 'OLD_GID=%q\n' "$OLD_GID"
  printf 'OLD_GROUP=%q\n' "$OLD_GROUP"
  printf 'RENAME_GROUP=%q\n' "$RENAME_GROUP"
  printf 'OLD_HOME=%q\n' "$OLD_HOME"
  printf 'NEW_HOME=%q\n' "$NEW_HOME"
  printf 'OLD_HOSTNAME=%q\n' "$OLD_HOSTNAME"
  printf 'NEW_HOSTNAME=%q\n' "$NEW_HOSTNAME"
  printf 'BACKUP_DIR=%q\n' "$BACKUP_DIR"
} > "$STATE_FILE"
chmod 0600 "$STATE_FILE"
chown root:root "$STATE_FILE"

cat > "$UNIT_FILE" <<EOF
[Unit]
Description=Robotinit offline account and machine identity rename
After=local-fs.target
Before=systemd-user-sessions.service getty.target display-manager.service ssh.service sshd.service ssh.socket sshd.socket
ConditionPathExists=${STATE_FILE}

[Service]
Type=oneshot
ExecStart=${APPLY_SCRIPT} --apply ${STATE_FILE}
TimeoutStartSec=30min
StandardOutput=journal+console
StandardError=journal+console

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$UNIT_FILE"
systemctl daemon-reload
systemctl enable "$UNIT_NAME" >/dev/null
printf 'status=staged\nstaged-at=%s\n' \
  "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "${WORK_DIR}/status"
sync
STAGING=0
trap - ERR

if ((NO_REBOOT)); then
  echo "迁移任务已投递。请尽快手动执行 sudo reboot；完成前不要创建同名账户或 home。"
  exit 0
fi

echo "迁移任务已投递，系统将在 5 秒后开始第一次重启。"
echo "第二次启动完成后，请使用 ${NEW_USER}@${NEW_HOSTNAME} 登录并更新客户端 known_hosts。"
sleep 5
if ! systemctl reboot; then
  echo "自动重启失败；任务已经投递，请立即手动执行 sudo reboot。" >&2
  exit 1
fi
